framework:
  workflows:
    cleaning_workflow:
      type: 'state_machine' # or 'state_machine'
      marking_store:
        type: 'method'
        property: 'cleaningState'
      supports: App\Entity\Chambres
      places:
        - clean
        - dirty
      transitions:
        to_clean:
          from: dirty
          to: clean
        to_dirty:
          from: clean
          to: dirty